---
title: "MLDS Research Project"
subtitle: "Phase 1 - Base Cases"
output:
  html_document:
    toc: true
    toc_depth: 2
    theme: united
    number_sections: true
date: "5th July 2023"
geometry: "left=1cm,right=1cm,top=1cm,bottom=2cm"
author: "James Lee (CID: 01185042)"
bibliography: ref.bib
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
```


```{r}
setwd("~/coding/mlds-final-project/Research/coarsening")
source("../utils.R", local = knitr::knit_global())
```

Imports
```{r}
library(tidyverse)
library(glue)
library(rlist)
library(rhdf5)
library(reshape2)

library(mvtnorm)
library(LaplacesDemon)
library(sn)
```

```{r}
K_0 <- 2
ns <- c(100, 250, 500, 1000, 2500, 5000, 10000)
alphas <- c("10.0", "100.0", "1000.0", "10000.0", "100000.0", "1.0e6", "Inf")
m <- 10
pmf <- matrix(NA, nrow = m, ncol = length(ns))

for (i_a in seq_along(alphas)) {
    alpha <- alphas[i_a]
    for (i_n in seq_along(ns)) {
        n <- ns[i_n]
        sep_string <- format(sep, nsmall = 1)
        k_posteriors <- h5read(glue("./comp_outputs/k_posteriors-alpha={alpha}-n={n}-skew_norm_mixtures.jld"), "k_posteriors")
        pmf[, i_n] <- rowMeans(k_posteriors[1:m, ])
    }

    df <- as.data.frame(cbind(1:m, pmf))
    colnames(df) <- c("k", ns)
    long_df <- melt(df, id.vars = "k", variable.name = "series")
    colnames(long_df) <- c("k", "samples", "pmf")
    pmf_plot <- long_df %>%
        ggplot(aes(x = k, y = pmf)) +
        geom_line(aes(colour = samples), linewidth = 1) +
        geom_point(aes(colour = samples)) +
        geom_vline(xintercept = K_0, linetype = "dotted", linewidth = 1.5) +
        scale_x_continuous(name = "k", breaks = 1:m)
    print(pmf_plot)
}
```

```{r}
K_0 <- 2
ns <- c(100, 250, 500, 1000, 2500, 5000, 10000)
alphas <- c("10.0", "100.0", "1000.0", "10000.0", "100000.0", "Inf")
m <- 10
pmf <- matrix(NA, nrow = m, ncol = length(ns))

for (i_a in seq_along(alphas)) {
    alpha <- alphas[i_a]
    for (i_n in seq_along(ns)) {
        n <- ns[i_n]
        sep_string <- format(sep, nsmall = 1)
        k_posteriors <- h5read(glue("./comp_outputs/skew_norm/1d/k_posteriors-single_skew_normal_1d-coarsen={alpha}-alpha=7-n={n}-set=1.jld"), "k_posteriors")
        pmf[, i_n] <- rowMeans(k_posteriors[1:m, ])
    }

    df <- as.data.frame(cbind(1:m, pmf))
    colnames(df) <- c("k", ns)
    long_df <- melt(df, id.vars = "k", variable.name = "series")
    colnames(long_df) <- c("k", "samples", "pmf")
    pmf_plot <- long_df %>%
        ggplot(aes(x = k, y = pmf)) +
        geom_line(aes(colour = samples), linewidth = 1) +
        geom_point(aes(colour = samples)) +
        geom_vline(xintercept = K_0, linetype = "dotted", linewidth = 1.5) +
        scale_x_continuous(name = "k", breaks = 1:m)
    print(pmf_plot)
}
```





```{r}
K_0 <- 2
ns <- c(100, 250, 500, 1000, 2500, 5000, 10000)
alphas <- c("10.0", "100.0", "1000.0", "10000.0", "100000.0", "Inf")
m <- 10
pmf <- matrix(NA, nrow = m, ncol = length(ns))

for (i_a in seq_along(alphas)) {
    alpha <- alphas[i_a]
    for (i_n in seq_along(ns)) {
        n <- ns[i_n]
        sep_string <- format(sep, nsmall = 1)
        k_posteriors <- h5read(glue("./comp_outputs/k_posteriors-alpha={alpha}-n={n}-student_t_mixtures.jld"), "k_posteriors")
        pmf[, i_n] <- rowMeans(k_posteriors[1:m, ])
    }

    df <- as.data.frame(cbind(1:m, pmf))
    colnames(df) <- c("k", ns)
    long_df <- melt(df, id.vars = "k", variable.name = "series")
    colnames(long_df) <- c("k", "samples", "pmf")
    pmf_plot <- long_df %>%
        ggplot(aes(x = k, y = pmf)) +
        geom_line(aes(colour = samples), linewidth = 1) +
        geom_point(aes(colour = samples)) +
        geom_vline(xintercept = K_0, linetype = "dotted", linewidth = 1.5) +
        scale_x_continuous(name = "k", breaks = 1:m)
    print(pmf_plot)
}
```
```{r}
K_0 <- 2
ns <- c(100, 250, 500, 1000, 2500)
alphas <- c("10.0", "100.0")
seps <- seq(1, 5, 0.5)
m <- 10
pmf <- matrix(NA, nrow = m, ncol = length(seps))

for (i_n in seq_along(ns)) {
    n <- ns[i_n]
    for (i_a in seq_along(alphas)) {
        alpha <- alphas[i_a]
        for (i_sep in seq_along(seps)) {
            sep <- seps[i_sep]
            sep_string <- format(sep, nsmall = 1)
            k_posteriors <- h5read(glue("./comp_outputs/k_posteriors-alpha={alpha}-n={n}-sep={sep_string}-1d_skew_norm_mixtures.jld"), "k_posteriors")
            pmf[, i_sep] <- rowMeans(k_posteriors[1:m, ])
        }

        df <- as.data.frame(cbind(1:m, pmf))
        colnames(df) <- c("k", seps)
        long_df <- melt(df, id.vars = "k", variable.name = "series")
        colnames(long_df) <- c("k", "separation", "pmf")
        title <- glue("1D Skew Norm Mixture - 2 components - alpha={alpha} - n={n}")
        pmf_plot <- long_df %>%
            ggplot(aes(x = k, y = pmf)) +
            geom_line(aes(colour = separation), linewidth = 1) +
            geom_point(aes(colour = separation)) +
            geom_vline(xintercept = K_0, linetype = "dotted", linewidth = 1.5) +
            scale_x_continuous(name = "k", breaks = 1:m) +
            ggtitle(title)

        print(pmf_plot)
    }
}
```

```{r}
K_0 <- 2
ns <- c(100, 250, 500, 1000, 2500, 5000, 10000)
alphas <- c("10.0", "100.0", "1000.0", "10000.0", "Inf")
seps <- seq(1, 5, 0.5)
m <- 10
pmf <- matrix(NA, nrow = m, ncol = length(seps))

for (i_n in seq_along(ns)) {
    n <- ns[i_n]
    for (i_a in seq_along(alphas)) {
        alpha <- alphas[i_a]
        for (i_sep in seq_along(seps)) {
            sep <- seps[i_sep]
            sep_string <- format(sep, nsmall = 1)
            k_posteriors <- h5read(glue("./comp_outputs/k_posteriors-alpha={alpha}-n={n}-sep={sep_string}-1d_laplace_mixtures.jld"), "k_posteriors")
            pmf[, i_sep] <- rowMeans(k_posteriors[1:m, ])
        }

        df <- as.data.frame(cbind(1:m, pmf))
        colnames(df) <- c("k", seps)
        long_df <- melt(df, id.vars = "k", variable.name = "series")
        colnames(long_df) <- c("k", "separation", "pmf")
        title <- glue("1D Skew Norm Mixture - 2 components - alpha={alpha} - n={n}")
        pmf_plot <- long_df %>%
            ggplot(aes(x = k, y = pmf)) +
            geom_line(aes(colour = separation), linewidth = 1) +
            geom_point(aes(colour = separation)) +
            geom_vline(xintercept = K_0, linetype = "dotted", linewidth = 1.5) +
            scale_x_continuous(name = "k", breaks = 1:m) +
            ggtitle(title)

        print(pmf_plot)
    }
}
```



```{r}
plot_avg_map_k <- function(coarsen, ns, m, K_0, dim) {
  pmf = matrix(NA, nrow = m, ncol = length(sets))
  avg_map_k = rep(NA, length(ns))
  
  for (i_n in seq_along(ns)) {
    n = ns[i_n]
    
    for (i_set in seq_along(sets)) {
      set = sets[i_set]
      filename = glue("./comp_outputs/skew_norm/{dim}d/k_posterior-single_skew_normal_{dim}d-coarsen={coarsen}-alpha=7-n={n}-set-{set}.jld")
      k_posterior = h5read(filename, "k_posterior")
      pmf[, i_set] = k_posterior[1:m]
    }
    
    df = as.data.frame(cbind(1:m, pmf))
    colnames(df) = c("k", sets)
    long_df = melt(df,  id.vars = "k", variable.name = "series")
    colnames(long_df) = c("k", "set", "pmf")
  
    pmf_plot = long_df %>%
      ggplot(aes(x = k, y = pmf)) +
      geom_line(aes(colour = set), linewidth = 1) +
      geom_point(aes(color = set)) +
      geom_vline(xintercept = K_0, linetype = "dotted", linewidth = 1.5) +
      scale_x_continuous(name = "k", breaks = 1:m) +
      ggtitle(glue("MFM - 1D Laplace - 1 component - n={n}")) +
      scale_color_grey(start = 0.7, end = 0)
    # print(pmf_plot)
    map_k = apply(pmf, 2, which.max)
    avg_map_k[i_n] = mean(map_k)
  }
  return(avg_map_k)
}

sets = 1:50
ns = c(100, 250, 500, 750)
m = 10
K_0 = 1
coarsen = c(10, 50, 70, 80, 100, 1000)
# alphas = c(2, 5, 10, 50, 1000)
df = as.data.frame(
  cbind(
    ns,
    plot_avg_map_k(10, ns, m, K_0, 1),
    plot_avg_map_k(50, ns, m, K_0, 1),
    plot_avg_map_k(70, ns, m, K_0, 1),
    plot_avg_map_k(80, ns, m, K_0, 1),
    plot_avg_map_k(100, ns, m, K_0, 1),
    plot_avg_map_k(1000, ns, m, K_0, 1)
  )
)
colnames(df) <- c("n", coarsen)
long_df = melt(df,  id.vars = "n", variable.name = "coarsen")
colnames(long_df) = c("n", "coarsen", "avg_map_k")
pmf_plot = long_df %>%
  ggplot(aes(x = n, y = avg_map_k)) +
  geom_line(aes(colour = coarsen), linewidth = 1) +
  geom_point(aes(color = coarsen)) +
  scale_x_continuous(name = "n") +
  scale_color_grey(start=0.7, end=0)
print(pmf_plot)
```






