---
title: "MLDS Research Project"
subtitle: "Single Component Study"
output:
  html_document:
    toc: true
    toc_depth: 2
    theme: united
    number_sections: true
date: "8th August 2023"
geometry: "left=1cm,right=1cm,top=1cm,bottom=2cm"
author: "James Lee (CID: 01185042)"
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
setwd("~/coding/mlds-final-project/Research/single_component")
```

Imports
```{r imports}
library(tidyverse)
library(glue)
library(rlist)
library(rhdf5)
library(reshape2)

library(mvtnorm)
library(LaplacesDemon)
library(sn)
library(mnormt)

library(ggpubr)
library(gridExtra)

library(mcclust.ext)

set.seed(0)
```



# Skew Normal
## Create a single skew normal distribution
```{r}
omega = 1
alphas = c(0, 1, 2, 5, 7)
xi = 0
n = 10000

for (alpha in alphas) {
  for (set in 1:50) {
    data = rsn(n = n, xi = xi, omega = omega, alpha = alpha)
    save_name = glue("./data_inputs/skew_norm/1d/single_skew_normal_1d-alpha={alpha}-set-{set}.jld")
    # h5save(data, file = save_name, name = "data")
  }
}

set = 1
for (alpha in alphas) {
  read_name = glue("./data_inputs/skew_norm/1d/single_skew_normal_1d-alpha={alpha}-set-{set}.jld")
  df = as.data.frame(h5read(read_name, "data"))
  colnames(df) = c("x")
  p = df %>% ggplot(aes(x = x)) + 
    geom_histogram(bins = 20, fill = "#619cff", color = "#000000", alpha = 0.9) + 
    theme(plot.title = element_text(size = 10), text = element_text(size = 20))
  print(p)
  ggsave(
    glue("./plots/single_skew_normal_1d_examples-alpha={alpha}.pdf"),
    p,
    width = 5,
    height = 5,
    dpi = 600,
    units = "in",
    device = "pdf"
  )
}
```

```{r}
Omega = matrix(c(1, 0, 0, 1), nrow = 2, ncol = 2)
alphas = c(0, 1, 2, 5, 7)
xi = c(0, 0)
n = 10000

for (alpha in alphas) {
  for (set in 1:50) {
    data = rmsn(n = n, xi = xi, Omega = Omega, alpha = c(alpha, alpha))
    save_name = glue("./data_inputs/skew_norm/2d/single_skew_normal_2d-alpha={alpha}-set-{set}.jld")
    # h5save(data, file = save_name, name = "data")
  }
}

set = 1
for (alpha in alphas) {
  read_name = glue("./data_inputs/skew_norm/2d/single_skew_normal_2d-alpha={alpha}-set-{set}.jld")
  
  df = as.data.frame(h5read(read_name, "data"))
  colnames(df) = c("x", "y")
  p = df %>% ggplot(aes(x = x, y = y)) +
    geom_point(size = 0.1, color="#619CFF") + 
    theme(plot.title = element_text(size = 10), text = element_text(size = 20))
  print(p)
  ggsave(
    glue("./plots/single_skew_normal_2d_examples-alpha={alpha}.pdf"),
    p,
    width = 5,
    height = 5,
    dpi = 600,
    units = "in",
    device = "pdf"
  )
}
```
```{r}
set = 1
alpha = 7
ns = c(100, 500, 1000, 5000)
for (n in ns) {
  read_name = glue("./data_inputs/skew_norm/2d/single_skew_normal_2d-alpha={alpha}-set-{set}.jld")
  df = as.data.frame(h5read(read_name, "data")[1:n, ])
  colnames(df) = c("x", "y")
  p = df %>% ggplot(aes(x = x, y = y)) +
    geom_point(size = 1, color="#619CFF") + 
    xlim(-5, 5) +
    ylim(-5, 5) +
    theme(plot.title = element_text(size = 15), text = element_text(size = 20))
  print(p)
  ggsave(
    glue("./plots/single_skew_normal_2d_examples-alpha=7-n={n}.pdf"),
    p,
    width = 5,
    height = 5,
    dpi = 600,
    units = "in",
    device = "pdf"
  )
}
```


Single Skew Normal Results
```{r}
m = 10
set = 8
dim = 2
K_0 = 1
ns = c(100, 250, 500, 750, 1000, 1500, 2500, 5000, 7500, 10000)
alpha = 5
pmf = matrix(NA, nrow = m, ncol = length(ns))

for (i_n in seq_along(ns)) {
  n = ns[i_n]
  filename = glue("./comp_outputs/skew_norm/{dim}d/k_posterior-single_skew_normal_{dim}d-alpha={alpha}-n={n}-set-{set}.jld")
  k_posterior = h5read(filename, "k_posterior")
  pmf[, i_n] = k_posterior[1:m]
}

df = as.data.frame(cbind(1:m, pmf))
colnames(df) = c("k", ns)
long_df = melt(df,  id.vars = "k", variable.name = "series")
colnames(long_df) = c("k", "n", "pmf")

pmf_plot = long_df %>%
  # filter(set) %>%
  ggplot(aes(x = k, y = pmf)) +
  geom_line(aes(colour = n), linewidth = 1) +
  geom_point(aes(color = n)) +
  geom_vline(xintercept = K_0, linetype = "dotted", linewidth = 1.5) +
  scale_x_continuous(name = "k", breaks = 1:m) +
  theme(text = element_text(size = 15)) +
  ylab("p(k | X)") +
  ggtitle(glue("Posterior pmf of no. of components - alpha={alpha} - set {set} of 50"))
print(pmf_plot)
ggsave("./plots/example_pmfs.pdf", pmf_plot, width=10, height=5, units="in", dpi=600, device="pdf")
```


```{r}
plot_avg_map_k <- function(alpha, ns, m, K_0, dim, sets) {
  pmf = matrix(NA, nrow = m, ncol = length(sets))
  avg_map_k = rep(NA, length(ns))
  
  for (i_n in seq_along(ns)) {
    n = ns[i_n]
    
    for (i_set in seq_along(sets)) {
      set = sets[i_set]
      filename = glue("./comp_outputs/skew_norm/{dim}d/k_posterior-single_skew_normal_{dim}d-alpha={alpha}-n={n}-set-{set}.jld")
      k_posterior = h5read(filename, "k_posterior")
      pmf[, i_set] = k_posterior[1:m]
    }
    
    map_k = apply(pmf, 2, which.max)
    avg_map_k[i_n] = mean(map_k)
  }
  return(avg_map_k)
}

ns = c(100, 250, 500, 750, 1000, 1500, 2500, 5000, 7500, 10000)
alphas = c(0, 1, 2, 5, 7)
sets = 1:50
m = 10
K_0 = 1
df = as.data.frame(
  cbind(
    ns,
    plot_avg_map_k(0, ns, m, K_0, 1, sets),
    plot_avg_map_k(1, ns, m, K_0, 1, sets),
    plot_avg_map_k(2, ns, m, K_0, 1, sets),
    plot_avg_map_k(5, ns, m, K_0, 1, sets),
    plot_avg_map_k(7, ns, m, K_0, 1, sets)
  )
)
colnames(df) <- c("n", alphas)
long_df = melt(df,  id.vars = "n", variable.name = "alpha")
colnames(long_df) = c("n", "alpha", "avg_map_k")
pmf_plot_1d = long_df %>%
  ggplot(aes(x = log(n), y = avg_map_k)) +
  geom_line(aes(colour = alpha), linewidth = 1) +
  geom_point(aes(color = alpha)) +
  scale_color_grey(start=0.7, end=0) +
  scale_x_continuous(name = "log(n)") +
  scale_y_continuous("Average MAP number of components", 1:6, limits = c(1, 6)) +
  ggtitle("Single 1D Skew Normal Component") +
  geom_hline(yintercept=K_0, linetype = 'dotted', col = 'blue')

df = as.data.frame(
  cbind(
    ns,
    plot_avg_map_k(0, ns, m, K_0, 2, sets),
    plot_avg_map_k(1, ns, m, K_0, 2, sets),
    plot_avg_map_k(2, ns, m, K_0, 2, sets),
    plot_avg_map_k(5, ns, m, K_0, 2, sets),
    plot_avg_map_k(7, ns, m, K_0, 2, sets)
  )
)
colnames(df) <- c("n", alphas)
long_df = melt(df,  id.vars = "n", variable.name = "alpha")
colnames(long_df) = c("n", "alpha", "avg_map_k")
pmf_plot_2d = long_df %>%
  ggplot(aes(x = log(n), y = avg_map_k)) +
  geom_line(aes(colour = alpha), linewidth = 1) +
  geom_point(aes(color = alpha)) +
  scale_color_grey(start = 0.7, end = 0) +
  scale_x_continuous(name = "log(n)") +
  scale_y_continuous("Average MAP number of components", 1:6, limits = c(1, 6)) +
  ggtitle("Single 2D Skew Normal Component") +
  geom_hline(yintercept=K_0, linetype = 'dotted', col = 'blue')

print(pmf_plot_1d)
print(pmf_plot_2d)
p = ggarrange(pmf_plot_1d, pmf_plot_2d, ncol = 2)
print(p)
ggsave("./plots/single_skew_normal_results.pdf", p, width=10, height=5, units="in", dpi=600, device="pdf")
```




```{r}
dofs = c(2, 5, 10, 50, 1000)
n = 10000
for (dof in dofs) {
  for (set in 1:50) {
    data = rt(n = n, df = dof)
    save_name = glue("./data_inputs/student_t/1d/single_t_1d-dof={dof}-set-{set}.jld")
    # h5save(data, file = save_name, name = "data")
  }
}

set = 1
for (dof in dofs) {
  read_name = glue("./data_inputs/student_t/1d/single_t_1d-dof={dof}-set-{set}.jld")
  df = as.data.frame(h5read(read_name, "data"))
  colnames(df) = c("x")
  p = df %>% ggplot(aes(x = x)) +
    geom_histogram(bins = 20, fill = "#619cff", color = "#000000", alpha = 0.9) + 
    theme(text = element_text(size = 20))
  print(p)
  ggsave(
    glue("./plots/single_t_1d_examples-dof={dof}.pdf"),
    p,
    width = 5,
    height = 5,
    dpi = 600,
    units = "in",
    device = "pdf"
  )
}
```



```{r}
loc = c(0, 0)
scale = matrix(c(1, 0, 0, 1), nrow = 2)
dofs = c(2, 5, 10, 50, 1000)

for (dof in dofs) {
  for (set in 1:50) {
    data = rmt(n = 10000, mean = loc, S = scale, df = dof)
    save_name = glue("./data_inputs/student_t/2d/single_t_2d-dof={dof}-set-{set}.jld")
    # h5save(data, file = save_name, name = "data")
  }
}

set = 1
for (dof in dofs) {
  read_name = glue("./data_inputs/student_t/2d/single_t_2d-dof={dof}-set-{set}.jld")
  
  df = as.data.frame(h5read(read_name, "data"))
  colnames(df) = c("x", "y")
  p = df %>% ggplot(aes(x = x, y = y)) +
    geom_point(size = 0.1, color = "#619CFF") + 
    theme(text = element_text(size = 20))
  print(p)
  ggsave(
    glue("./plots/single_t_2d_examples-dof={dof}.pdf"),
    p,
    width = 5,
    height = 5,
    dpi = 600,
    units = "in",
    device = "pdf"
  )
}
```

```{r}
plot_avg_map_k <- function(dof, ns, m, K_0, dim) {
  pmf = matrix(NA, nrow = m, ncol = length(sets))
  avg_map_k = rep(NA, length(ns))
  
  for (i_n in seq_along(ns)) {
    n = ns[i_n]
    
    for (i_set in seq_along(sets)) {
      set = sets[i_set]
      filename = glue("./comp_outputs/student_t/{dim}d/k_posterior-single_t_{dim}d-dof={dof}-n={n}-set-{set}.jld")
      k_posterior = h5read(filename, "k_posterior")
      pmf[, i_set] = k_posterior[1:m]
    }
    
    df = as.data.frame(cbind(1:m, pmf))
    colnames(df) = c("k", sets)
    long_df = melt(df,  id.vars = "k", variable.name = "series")
    colnames(long_df) = c("k", "set", "pmf")
  
    pmf_plot = long_df %>%
      ggplot(aes(x = k, y = pmf)) +
      geom_line(aes(colour = set), linewidth = 1) +
      geom_point(aes(color = set)) +
      geom_vline(xintercept = K_0, linetype = "dotted", linewidth = 1.5) +
      scale_x_continuous(name = "k", breaks = 1:m) +
      ggtitle(glue("MFM - 1D Laplace - 1 component - n={n}")) +
      scale_color_grey(start = 0.7, end = 0)
    map_k = apply(pmf, 2, which.max)
    avg_map_k[i_n] = mean(map_k)
  }
  return(avg_map_k)
}

sets = 1:50
ns = c(100, 250, 500, 750, 1000, 1500, 2500, 5000, 7500, 10000)
m = 10
K_0 = 1
alphas = c(2, 5, 10, 50, 1000)
df = as.data.frame(
  cbind(
    ns,
    plot_avg_map_k(2, ns, m, K_0, 1),
    plot_avg_map_k(5, ns, m, K_0, 1),
    plot_avg_map_k(10, ns, m, K_0, 1),
    plot_avg_map_k(50, ns, m, K_0, 1),
    plot_avg_map_k(1000, ns, m, K_0, 1)
  )
)
colnames(df) <- c("n", alphas)
long_df = melt(df,  id.vars = "n", variable.name = "alpha")
colnames(long_df) = c("n", "dof", "avg_map_k")
pmf_plot_1d = long_df %>%
  ggplot(aes(x = log(n), y = avg_map_k)) +
  geom_line(aes(colour = dof), linewidth = 1) +
  geom_point(aes(color = dof)) +
  scale_x_continuous(name = "log(n)") +
  scale_color_grey(start = 0, end = 0.7) +
  scale_y_continuous("Average MAP number of components", 1:6, limits = c(1, 6)) +
  ggtitle("Single 1D t Component") +
  geom_hline(yintercept=K_0, linetype = 'dotted', col = 'blue')
print(pmf_plot_1d)

df = as.data.frame(
  cbind(
    ns,
    plot_avg_map_k(2, ns, m, K_0, 2),
    plot_avg_map_k(5, ns, m, K_0, 2),
    plot_avg_map_k(10, ns, m, K_0, 2),
    plot_avg_map_k(50, ns, m, K_0, 2),
    plot_avg_map_k(1000, ns, m, K_0, 2)
  )
)
colnames(df) <- c("n", alphas)
long_df = melt(df,  id.vars = "n", variable.name = "alpha")
colnames(long_df) = c("n", "dof", "avg_map_k")
pmf_plot_2d = long_df %>%
  ggplot(aes(x = log(n), y = avg_map_k)) +
  geom_line(aes(colour = dof), linewidth = 1) +
  geom_point(aes(color = dof)) +
  scale_x_continuous(name = "log(n)") +
  scale_color_grey(start = 0, end = 0.7) +
  scale_y_continuous("Average MAP number of components", 1:6, limits = c(1, 6)) +
  ggtitle("Single 2D t Component") +
  geom_hline(yintercept=K_0, linetype = 'dotted', col = 'blue')
print(pmf_plot_2d)

p = ggarrange(pmf_plot_1d, pmf_plot_2d, ncol = 2)
print(p)
ggsave("./plots/single_t_results.pdf", p, width=10, height=5, units="in", dpi=600, device="pdf")
```

# Checking convergence
```{r}
filename = glue("./convergence_checks/ts.jld")
t_r = h5read(filename, "t_r")

mcmc_its = 10^5
mcmc_burn = 5 * 10^4
mcmc_keep = mcmc_its - mcmc_burn

df = as.data.frame(cbind(1:100000, t_r))
df$class = as.factor(c(rep("burn", mcmc_burn), rep("keep", mcmc_keep)))
colnames(df) = c("iter", "t", "class")

p = df %>% 
  mutate(rec = 1) %>% 
  mutate(rollavg = cumsum(t)/cumsum(rec)) %>% 
  select(-rec) %>%
  ggplot() + 
  geom_point(aes(x = iter, y = rollavg, color=class), size = 0.5) +
  scale_y_continuous("Avg. posterior number of clusters") +
  scale_x_continuous("iterations", seq(0, 100000, 25000)) +
  ggtitle("Running posterior average number of clusters vs. MCMC iterations")
print(p)
ggsave("./plots/posterior_average_convergence_check.pdf", p, width=10, height=5, units="in", dpi=600, device="pdf")
```


# Visualise some posterior clusterings

```{r}
mcmc_its = 100000
mcmc_burn = 10000
set = 8
alpha = 7
ns = c(100, 500, 1000)

read_name = glue("./data_inputs/skew_norm/2d/single_skew_normal_2d-alpha={alpha}-set-{set}.jld")
all_data = h5read(
  read_name,
  "data"
)


for (n in ns) {

  data = all_data[1:n, ]
  
  post_z_samples = h5read(
    glue("./comp_outputs/skew_norm/2d/z_draws-single_skew_normal_2d-alpha={alpha}-n={n}-set-{set}.jld"),
    "z"
  )
  post_z_samples = t(post_z_samples[, (mcmc_burn + 1):mcmc_its])
  
  psm = comp.psm(post_z_samples)
  min_vi = minVI(
    psm,
    post_z_samples,
    method = "draws",
    include.greedy = FALSE
  )
  best_vi = min_vi$cl

  # Create 
  df = as.data.frame(cbind(data, best_vi))
  colnames(df) = c("x", "y", "z")
  df$z = as.factor(df$z)

  summary_clustering_plot = df %>% ggplot(aes(x = x, y = y)) +
    geom_point(aes(color = z), size = 0.5) +
    scale_color_discrete() +
    ggtitle(glue("Summary Clustering (Best VILB Sample) - n={n}"))
  print(summary_clustering_plot)
  ggsave(
    glue("./plots/single_skew_norm_summary_clustering_n={n}.pdf"),
    summary_clustering_plot, width=10, height=5, units="in", dpi=600, device="pdf")
}
```

Student's t summary clustering
```{r}
mcmc_its = 100000
mcmc_burn = 10000
set = 8
dof = 2
ns = c(100, 500, 1000)

read_name = glue("./data_inputs/student_t/2d/single_t_2d-dof={dof}-set-{set}.jld")
all_data = h5read(
  read_name,
  "data"
)


for (n in ns) {
  data = all_data[1:n, ]
  post_z_samples = h5read(
    glue("./comp_outputs/student_t/2d/z_draws-single_t_2d-dof={dof}-n={n}-set-{set}.jld"),
    "z"
  )
  post_z_samples = t(post_z_samples[, (mcmc_burn + 1):mcmc_its])
  
  psm = comp.psm(post_z_samples)
  min_vi = minVI(
    psm,
    post_z_samples,
    method = "draws",
    include.greedy = FALSE
  )
  best_vi = min_vi$cl

  # Create 
  df = as.data.frame(cbind(data, best_vi))
  colnames(df) = c("x", "y", "z")
  df$z = as.factor(df$z)

  summary_clustering_plot = df %>% ggplot(aes(x = x, y = y)) +
    geom_point(aes(color = z), size = 0.5) +
    scale_color_discrete() +
    ggtitle(glue("Summary Clustering (Best VILB Sample) - n={n}"))
  print(summary_clustering_plot)
  ggsave(glue("./plots/single_t_summary_clustering_n={n}.pdf"), summary_clustering_plot, width=10, height=5, units="in", dpi=600, device="pdf")
}

```









# Single Laplace component
## Create data
### 2D
```{r}
ss = c(1, 2, 3, 4, 5)
mu = c(0, 0)
n = 10000

for (s in ss) {
  sigma =  matrix(c(s, 0, 0, s), nrow = 2, ncol = 2)
  for (set in 1:50) {
    data = rmvl(n = n, mu=mu, Sigma = sigma)
    save_name = glue("./data_inputs/laplace/2d/single_laplace_2d-sigma={s}-set-{set}.jld")
    # h5save(data, file = save_name, name = "data")
  }
}

plot_created_data <- list()
for (s in ss) {
  for (set in 1:3) {
    read_name = glue("./data_inputs/laplace/2d/single_laplace_2d-sigma={s}-set-{set}.jld")
    
    plot_created_data[[read_name]]

    df = as.data.frame(h5read(read_name, "data"))
    colnames(df) = c("x", "y")
    plot_created_data[[read_name]] = df %>% ggplot(aes(x = x, y = y)) +
      geom_point(size = 0.1, color="#619CFF") + 
      ggtitle(glue("sigma={s} - set={set}")) +
      theme(plot.title = element_text(size = 10))
  }
}

p = do.call("grid.arrange", c(plot_created_data, ncol = 3))
ggsave(
  "./plots/single_laplace_2d_examples.pdf",
  p,
  width = 6,
  height = 10,
  dpi = 600,
  units = "in",
  device = "pdf"
)
```

### 1D
```{r}
lambdas = c(1, 2, 3, 4, 5)
mu = 0
n = 10000

for (lambda in lambdas) {
  for (set in 1:50) {
    data = rlaplace(n = n, location = mu, scale = lambda)
    save_name = glue("./data_inputs/laplace/1d/single_laplace_1d-lambda={lambda}-set-{set}.jld")
    # h5save(data, file = save_name, name = "data")
  }
  read_name = glue("./data_inputs/laplace/1d/single_laplace_1d-lambda={lambda}-set-8.jld")
  df = as.data.frame(h5read(read_name, "data"))
  colnames(df) = c("x")
  p = df %>% ggplot(aes(x = x)) + 
    geom_histogram(bins = 50, fill = "#619cff", color = "#000000") + 
    ggtitle(glue("Single 1D Laplace Component - lambda={lambda}"))
  print(p)
}

plot_created_data <- list()
for (lambda in lambdas) {
  for (set in 1:3) {
    read_name = glue("./data_inputs/laplace/1d/single_laplace_1d-lambda={lambda}-set-{set}.jld")
    
    plot_created_data[[read_name]]

    df = as.data.frame(h5read(read_name, "data"))
    colnames(df) = c("x")
    plot_created_data[[read_name]] = df %>% ggplot(aes(x = x)) + 
      geom_histogram(bins = 50, fill = "#619cff", color = "#000000") + 
      ggtitle(glue("lambda={lambda} - set-{set}")) +
      theme(plot.title = element_text(size = 10))
  }
}

p = do.call("grid.arrange", c(plot_created_data, ncol = 3))
ggsave(
  "./plots/single_laplace_1d_examples.pdf",
  p,
  width = 6,
  height = 10,
  dpi = 600,
  units = "in",
  device = "pdf"
)
```

### Laplace results
```{r}
sets = 1:50
ns = c(100, 250, 500, 750, 1000, 1500, 2500, 5000, 7500, 10000)
m = 10
K_0 = 1

plot_avg_map_k <- function(alpha, ns, m, K_0, dim) {
  pmf = matrix(NA, nrow = m, ncol = length(sets))
  avg_map_k = rep(NA, length(ns))
  
  for (i_n in seq_along(ns)) {
    n = ns[i_n]
    
    for (i_set in seq_along(sets)) {
      set = sets[i_set]
      filename = glue("./comp_outputs/laplace/{dim}d/k_posterior-single_laplace_{dim}d-lambda={alpha}-n={n}-set-{set}.jld")
      k_posterior = h5read(filename, "k_posterior")
      pmf[, i_set] = k_posterior[1:m]
    }
    
    df = as.data.frame(cbind(1:m, pmf))
    colnames(df) = c("k", sets)
    long_df = melt(df,  id.vars = "k", variable.name = "series")
    colnames(long_df) = c("k", "set", "pmf")
  
    pmf_plot = long_df %>%
      ggplot(aes(x = k, y = pmf)) +
      geom_line(aes(colour = set), linewidth = 1) +
      geom_point(aes(color = set)) +
      geom_vline(xintercept = K_0, linetype = "dotted", linewidth = 1.5) +
      scale_x_continuous(name = "k", breaks = 1:m) +
      ggtitle(glue("MFM - 1D Laplace - 1 component - n={n}")) +
      scale_color_grey(start=0.7, end=0)
    # print(pmf_plot)
    map_k = apply(pmf, 2, which.max)
    avg_map_k[i_n] = mean(map_k)
  }
  return(avg_map_k)
}


alphas = c(1, 2, 3, 4, 5)
df = as.data.frame(
  cbind(
    ns,
    plot_avg_map_k(1, ns, m, K_0, 1),
    plot_avg_map_k(2, ns, m, K_0, 1),
    plot_avg_map_k(3, ns, m, K_0, 1),
    plot_avg_map_k(4, ns, m, K_0, 1),
    plot_avg_map_k(5, ns, m, K_0, 1)
  )
)
colnames(df) <- c("n", alphas)
long_df = melt(df,  id.vars = "n", variable.name = "alpha")
colnames(long_df) = c("n", "lambda", "avg_map_k")
pmf_plot_1d = long_df %>%
  ggplot(aes(x = n, y = avg_map_k)) +
  geom_line(aes(colour = lambda), linewidth = 1) +
  geom_point(aes(color = lambda)) +
  scale_x_continuous(name = "n") +
  scale_color_grey(start=0.7, end=0)
print(pmf_plot_1d)
# 
# 


plot_avg_map_k <- function(alpha, ns, m, K_0, dim) {
  pmf = matrix(NA, nrow = m, ncol = length(sets))
  avg_map_k = rep(NA, length(ns))
  
  for (i_n in seq_along(ns)) {
    n = ns[i_n]
    
    for (i_set in seq_along(sets)) {
      set = sets[i_set]
      filename = glue("./comp_outputs/laplace/{dim}d/k_posterior-single_laplace_{dim}d-sigma={alpha}-n={n}-set-{set}.jld")
      k_posterior = h5read(filename, "k_posterior")
      pmf[, i_set] = k_posterior[1:m]
    }
    
    df = as.data.frame(cbind(1:m, pmf))
    colnames(df) = c("k", sets)
    long_df = melt(df,  id.vars = "k", variable.name = "series")
    colnames(long_df) = c("k", "set", "pmf")
  
    pmf_plot = long_df %>%
      ggplot(aes(x = k, y = pmf)) +
      geom_line(aes(colour = set), linewidth = 1) +
      geom_point(aes(color = set)) +
      geom_vline(xintercept = K_0, linetype = "dotted", linewidth = 1.5) +
      scale_x_continuous(name = "k", breaks = 1:m) +
      ggtitle(glue("MFM - 1D Laplace - 1 component - n={n}")) +
      scale_color_grey(start=0.7, end=0)
    # print(pmf_plot)
    map_k = apply(pmf, 2, which.max)
    avg_map_k[i_n] = mean(map_k)
  }
  return(avg_map_k)
}

ns = c(100, 250, 500, 750, 1000, 1500, 2500, 5000, 7500)
alphas = c(1, 2, 3, 4, 5)
df = as.data.frame(
  cbind(
    ns,
    plot_avg_map_k(1, ns, m, K_0, 2),
    plot_avg_map_k(2, ns, m, K_0, 2),
    plot_avg_map_k(3, ns, m, K_0, 2),
    plot_avg_map_k(4, ns, m, K_0, 2),
    plot_avg_map_k(5, ns, m, K_0, 2)
  )
)
colnames(df) <- c("n", alphas)
long_df = melt(df,  id.vars = "n", variable.name = "alpha")
colnames(long_df) = c("n", "lambda", "avg_map_k")
pmf_plot_2d = long_df %>%
  ggplot(aes(x = n, y = avg_map_k)) +
  geom_line(aes(colour = lambda), linewidth = 1) +
  geom_point(aes(color = lambda)) +
  scale_x_continuous(name = "n") +
  scale_color_grey(start=0.7, end=0)
print(pmf_plot_2d)

ggarrange(pmf_plot_1d, pmf_plot_2d, nrow = 2)
```
