---
title: "MLDS Research Project"
subtitle: "Single Component Study"
output:
  html_document:
    toc: true
    toc_depth: 2
    theme: united
    number_sections: true
date: "8th August 2023"
geometry: "left=1cm,right=1cm,top=1cm,bottom=2cm"
author: "James Lee (CID: 01185042)"
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
setwd("~/coding/mlds-final-project/Research/single_component")
```

Imports
```{r imports}
library(tidyverse)
library(glue)
library(rlist)
library(rhdf5)
library(reshape2)
library(mvtnorm)
library(LaplacesDemon)
library(sn)
library(mnormt)
library(ggpubr)
library(gridExtra)
library(mcclust.ext)
set.seed(0)
```

# Skew Normal
## Create 1D single skew normal distribution
```{r}
omega = 1
alphas = c(0, 1, 2, 5, 7)
xi = 0
n = 10000

for (alpha in alphas) {
  for (set in 1:50) {
    data = rsn(n = n, xi = xi, omega = omega, alpha = alpha)
    save_name = glue("./data_inputs/skew_norm/1d/single_skew_normal_1d-alpha={alpha}-set-{set}.jld")
    # h5save(data, file = save_name, name = "data")
  }
}

set = 1
for (alpha in alphas) {
  read_name = glue("./data_inputs/skew_norm/1d/single_skew_normal_1d-alpha={alpha}-set-{set}.jld")
  df = as.data.frame(h5read(read_name, "data"))
  colnames(df) = c("x")
  p = df %>% ggplot(aes(x = x)) + 
    geom_histogram(bins = 20, fill = "#619cff", color = "#000000", alpha = 0.9) + 
    theme(plot.title = element_text(size = 10), text = element_text(size = 20))
  print(p)
  ggsave(
    glue("./plots/single_skew_normal_1d_examples-alpha={alpha}.pdf"),
    p,
    width = 5,
    height = 5,
    dpi = 600,
    units = "in",
    device = "pdf"
  )
}
```
## Create 2D single skew normal distribution
```{r}
Omega = matrix(c(1, 0, 0, 1), nrow = 2, ncol = 2)
alphas = c(0, 1, 2, 5, 7)
xi = c(0, 0)
n = 10000

for (alpha in alphas) {
  for (set in 1:50) {
    data = rmsn(n = n, xi = xi, Omega = Omega, alpha = c(alpha, alpha))
    save_name = glue("./data_inputs/skew_norm/2d/single_skew_normal_2d-alpha={alpha}-set-{set}.jld")
    # h5save(data, file = save_name, name = "data")
  }
}

set = 1
for (alpha in alphas) {
  read_name = glue("./data_inputs/skew_norm/2d/single_skew_normal_2d-alpha={alpha}-set-{set}.jld")
  
  df = as.data.frame(h5read(read_name, "data"))
  colnames(df) = c("x", "y")
  p = df %>% ggplot(aes(x = x, y = y)) +
    geom_point(size = 0.1, color="#619CFF") + 
    theme(plot.title = element_text(size = 10), text = element_text(size = 20))
  print(p)
  ggsave(
    glue("./plots/single_skew_normal_2d_examples-alpha={alpha}.pdf"),
    p,
    width = 5,
    height = 5,
    dpi = 600,
    units = "in",
    device = "pdf"
  )
}
```

Skew normal component with increasing sample size
```{r}
set = 1
alpha = 7
ns = c(100, 500, 1000, 5000)
for (n in ns) {
  read_name = glue("./data_inputs/skew_norm/2d/single_skew_normal_2d-alpha={alpha}-set-{set}.jld")
  df = as.data.frame(h5read(read_name, "data")[1:n, ])
  colnames(df) = c("x", "y")
  p = df %>% ggplot(aes(x = x, y = y)) +
    geom_point(size = 1, color="#619CFF") + 
    xlim(-5, 5) +
    ylim(-5, 5) +
    theme(plot.title = element_text(size = 15), text = element_text(size = 20))
  print(p)
  ggsave(
    glue("./plots/single_skew_normal_2d_examples-alpha=7-n={n}.pdf"),
    p,
    width = 5,
    height = 5,
    dpi = 600,
    units = "in",
    device = "pdf"
  )
}
```

Single Skew Normal Results
```{r}
m = 10
set = 1
dim = 2
K_0 = 1
ns = c(100, 250, 500, 750, 1000, 1500, 2500, 5000, 7500, 10000)
alpha = 5
pmf = matrix(NA, nrow = m, ncol = length(ns))

for (i_n in seq_along(ns)) {
  n = ns[i_n]
  filename = glue("./comp_outputs/skew_norm/{dim}d/k_posterior-single_skew_normal_{dim}d-alpha={alpha}-n={n}-set-{set}.jld")
  k_posterior = h5read(filename, "k_posterior")
  pmf[, i_n] = k_posterior[1:m]
}

df = as.data.frame(cbind(1:m, pmf))
colnames(df) = c("k", ns)
long_df = melt(df,  id.vars = "k", variable.name = "series")
colnames(long_df) = c("k", "n", "pmf")

pmf_plot = long_df %>%
  ggplot(aes(x = k, y = pmf)) +
  geom_line(aes(colour = n), linewidth = 0.5) +
  geom_point(aes(color = n), size = 3) +
  geom_vline(xintercept = K_0, linetype = "dotted", linewidth = 1) +
  scale_x_continuous(name = "k", breaks = 1:m) +
  theme(text = element_text(size = 15)) +
  ylab("p(k | X)") +
  ggtitle(glue("Posterior pmf of no. of components - alpha={alpha} - set {set} of 50"))
print(pmf_plot)
ggsave("./plots/example_pmfs.pdf", pmf_plot, width=10, height=5, units="in", dpi=600, device="pdf")
```

Skew Normal 1D Results
```{r}
ns = c(100, 250, 500, 750, 1000, 1500, 2500, 5000, 7500, 10000)
alphas = c(7, 5, 2, 1, 0)
sets = 1:50
m = 10
K_0 = 1
dim = 1

plot_avg_map_k <- function(alpha, ns, m, K_0, dim, sets) {
  pmf = matrix(NA, nrow = m, ncol = length(sets))
  avg_map_k = rep(NA, length(ns))
  sd_map_k = rep(NA, length(ns))
  
  for (i_n in seq_along(ns)) {
    n = ns[i_n]
    
    for (i_set in seq_along(sets)) {
      set = sets[i_set]
      filename = glue("./comp_outputs/skew_norm/{dim}d/k_posterior-single_skew_normal_{dim}d-alpha={alpha}-n={n}-set-{set}.jld")
      k_posterior = h5read(filename, "k_posterior")
      pmf[, i_set] = k_posterior[1:m]
    }
    
    map_k = apply(pmf, 2, which.max)
    avg_map_k[i_n] = mean(map_k)
    sd_map_k[i_n] = sd(map_k)
  }
  return(list(avg_map_k = avg_map_k, sd_map_k = sd_map_k))
}


mean_df = as.data.frame(ns)
for (alpha in alphas) {
  mean_df = cbind(mean_df, plot_avg_map_k(alpha, ns, m, K_0, dim, sets)$avg_map_k)
}
colnames(mean_df) <- c("n", alphas)

sd_df = as.data.frame(ns)
for (alpha in alphas) {
  sd_df = cbind(sd_df, plot_avg_map_k(alpha, ns, m, K_0, dim, sets)$sd_map_k)
}
colnames(sd_df) <- c("n", alphas)

mean_df_long = melt(mean_df,  id.vars = "n", variable.name = "alpha")
sd_df_long = melt(sd_df,  id.vars = "n", variable.name = "alpha")
colnames(mean_df_long) = c("n", "alpha", "avg_map_k")
colnames(sd_df_long) = c("n", "alpha", "sd_map_k")

skew_norm_1d_long = merge(x = mean_df_long, y = sd_df_long, by = c("n", "alpha"))
skew_norm_1d_long$upper = skew_norm_1d_long$avg_map_k + 2 * skew_norm_1d_long$sd_map_k
skew_norm_1d_long$lower = skew_norm_1d_long$avg_map_k - 2 * skew_norm_1d_long$sd_map_k

p = skew_norm_1d_long %>%
  ggplot(aes(x = log(n), y = avg_map_k)) +
  geom_line(aes(colour = alpha), linewidth = 1) +
  geom_point(aes(color = alpha)) +
  scale_x_continuous(name = "log(n)") +
  scale_y_continuous("Average MAP number of components", 0:7, limits = c(0, 7)) +
  ggtitle("Single 1D Skew Normal Component") +
  geom_hline(yintercept = K_0, linetype = 'dotted', col = 'blue') +
  theme(text = element_text(size = 15))
print(p)
ggsave(
  glue("./plots/single_skew_normal_1d_results.pdf"),
  p,
  width = 10,
  height = 5,
  dpi = 600,
  units = "in",
  device = "pdf"
)
```

```{r}
for (a in alphas) {
  df = skew_norm_1d_long %>%
      filter(alpha == a)
  p = df %>% ggplot(aes(x = log(n))) +
    geom_line(aes(colour = alpha, y = avg_map_k), linewidth = 1, show.legend = FALSE) +
    geom_line(aes(colour = alpha, y = upper), linewidth = 1, show.legend = FALSE) +
    geom_line(aes(colour = alpha, y = lower), linewidth = 1, show.legend = FALSE) +
    geom_point(aes(color = alpha, y = avg_map_k), show.legend = FALSE) +
    scale_x_continuous(name = "log(n)") +
    scale_y_continuous("Avg. MAP number of components", 1:7, limits = c(1, 7)) +
    ggtitle(glue("Single 1D Skew Normal Component - alpha={a}")) +
    geom_hline(yintercept = K_0, linetype = 'dotted', col = 'blue') +
    theme(text = element_text(size = 18))
    print(p)
  ggsave(
    glue("./plots/single_skew_normal_1d_results-alpha={a}.pdf"),
    p,
    width = 8,
    height = 5,
    dpi = 600,
    units = "in",
    device = "pdf"
  )
}
```

```{r}
plot_avg_map_k <- function(alpha, ns, m, K_0, dim, sets) {
  pmf = matrix(NA, nrow = m, ncol = length(sets))
  avg_map_k = rep(NA, length(ns))
  sd_map_k = rep(NA, length(ns))
  
  for (i_n in seq_along(ns)) {
    n = ns[i_n]
    
    for (i_set in seq_along(sets)) {
      set = sets[i_set]
      filename = glue("./comp_outputs/skew_norm/{dim}d/k_posterior-single_skew_normal_{dim}d-alpha={alpha}-n={n}-set-{set}.jld")
      k_posterior = h5read(filename, "k_posterior")
      pmf[, i_set] = k_posterior[1:m]
    }
    
    map_k = apply(pmf, 2, which.max)
    avg_map_k[i_n] = mean(map_k)
    sd_map_k[i_n] = sd(map_k)
  }
  return(list(avg_map_k = avg_map_k, sd_map_k = sd_map_k))
}

dim = 2
mean_df = as.data.frame(ns)
for (alpha in alphas) {
  mean_df = cbind(mean_df, plot_avg_map_k(alpha, ns, m, K_0, dim, sets)$avg_map_k)
}
colnames(mean_df) <- c("n", alphas)

sd_df = as.data.frame(ns)
for (alpha in alphas) {
  sd_df = cbind(sd_df, plot_avg_map_k(alpha, ns, m, K_0, dim, sets)$sd_map_k)
}
colnames(sd_df) <- c("n", alphas)

mean_df_long = melt(mean_df,  id.vars = "n", variable.name = "alpha")
colnames(mean_df_long) = c("n", "alpha", "avg_map_k")

sd_df_long = melt(sd_df,  id.vars = "n", variable.name = "alpha")
colnames(sd_df_long) = c("n", "alpha", "sd_map_k")

skew_norm_2d_long = merge(x = mean_df_long, y = sd_df_long, by = c("n", "alpha"))
skew_norm_2d_long$upper = skew_norm_2d_long$avg_map_k + 2 * skew_norm_2d_long$sd_map_k
skew_norm_2d_long$lower = skew_norm_2d_long$avg_map_k - 2 * skew_norm_2d_long$sd_map_k

p = skew_norm_2d_long %>%
  ggplot(aes(x = log(n), y = avg_map_k)) +
  geom_line(aes(colour = alpha), linewidth = 1) +
  geom_point(aes(color = alpha)) +
  scale_x_continuous(name = "log(n)") +
  scale_y_continuous("Average MAP number of components", 0:7, limits = c(0, 7)) +
  ggtitle("Single 2D Skew Normal Component") +
  geom_hline(yintercept = K_0, linetype = 'dotted', col = 'blue') +
  theme(text = element_text(size = 15))
print(p)
ggsave(
  glue("./plots/single_skew_normal_2d_results.pdf"),
  p,
  width = 10,
  height = 5,
  dpi = 600,
  units = "in",
  device = "pdf"
)
```

```{r}
for (a in alphas) {
  df = skew_norm_2d_long %>%
      filter(alpha == a)
  p = df %>% ggplot(aes(x = log(n))) +
    geom_line(aes(colour = alpha, y = avg_map_k), linewidth = 1, show.legend = FALSE) +
    geom_line(aes(colour = alpha, y = upper), linewidth = 1, show.legend = FALSE) +
    geom_line(aes(colour = alpha, y = lower), linewidth = 1, show.legend = FALSE) +
    geom_point(aes(color = alpha, y = avg_map_k), show.legend = FALSE) +
    scale_x_continuous(name = "log(n)") +
    scale_y_continuous("Avg. MAP number of components", 1:7, limits = c(1, 7)) +
    ggtitle(glue("Single 2D Skew Normal Component - alpha={a}")) +
    geom_hline(yintercept = K_0, linetype = 'dotted', col = 'blue') +
    theme(text = element_text(size = 18))
print(p)
  ggsave(
    glue("./plots/single_skew_normal_2d_results-alpha={a}.pdf"),
    p,
    width = 8,
    height = 5,
    dpi = 600,
    units = "in",
    device = "pdf"
  )
}
```

```{r}
skew_norm_both_df = merge(skew_norm_2d_long, skew_norm_1d_long, by = c("n", "alpha"))
skew_norm_both_df$diff = skew_norm_both_df$avg_map_k.x - skew_norm_both_df$avg_map_k.y
p = skew_norm_both_df %>%
  ggplot(aes(x = log(n), y = diff)) +
  geom_line(aes(colour = alpha), linewidth = 1) +
  geom_point(aes(color = alpha)) +
  scale_x_continuous(name = "log(n)") +
  scale_y_continuous("Difference in avg. MAP number of components") +
  ggtitle("Difference in average MAP number of components (2D minus 1D)") +
  theme(text = element_text(size = 15))
print(p)
ggsave(
  glue("./plots/single_skew_normal_2d_1d_diff.pdf"),
  p,
  width = 10,
  height = 5,
  dpi = 600,
  units = "in",
  device = "pdf"
)
```



## $t$-student
```{r}
dofs = c(2, 5, 10, 50, 1000)
n = 10000
for (dof in dofs) {
  for (set in 1:50) {
    data = rt(n = n, df = dof)
    save_name = glue("./data_inputs/student_t/1d/single_t_1d-dof={dof}-set-{set}.jld")
    # h5save(data, file = save_name, name = "data")
  }
}

set = 1
for (dof in dofs) {
  read_name = glue("./data_inputs/student_t/1d/single_t_1d-dof={dof}-set-{set}.jld")
  df = as.data.frame(h5read(read_name, "data"))
  colnames(df) = c("x")
  p = df %>% ggplot(aes(x = x)) +
    geom_histogram(bins = 20, fill = "#619cff", color = "#000000", alpha = 0.9) + 
    theme(text = element_text(size = 20))
  print(p)
  ggsave(
    glue("./plots/single_t_1d_examples-dof={dof}.pdf"),
    p,
    width = 5,
    height = 5,
    dpi = 600,
    units = "in",
    device = "pdf"
  )
}
```



```{r}
loc = c(0, 0)
scale = matrix(c(1, 0, 0, 1), nrow = 2)
dofs = c(2, 5, 10, 50, 1000)

for (dof in dofs) {
  for (set in 1:50) {
    data = rmt(n = 10000, mean = loc, S = scale, df = dof)
    save_name = glue("./data_inputs/student_t/2d/single_t_2d-dof={dof}-set-{set}.jld")
    # h5save(data, file = save_name, name = "data")
  }
}

set = 1
for (dof in dofs) {
  read_name = glue("./data_inputs/student_t/2d/single_t_2d-dof={dof}-set-{set}.jld")
  
  df = as.data.frame(h5read(read_name, "data"))
  colnames(df) = c("x", "y")
  p = df %>% ggplot(aes(x = x, y = y)) +
    geom_point(size = 0.1, color = "#619CFF") + 
    theme(text = element_text(size = 20))
  print(p)
  ggsave(
    glue("./plots/single_t_2d_examples-dof={dof}.pdf"),
    p,
    width = 5,
    height = 5,
    dpi = 600,
    units = "in",
    device = "pdf"
  )
}
```

```{r}
ns = c(100, 250, 500, 750, 1000, 1500, 2500, 5000, 7500, 10000)
dofs = c(2, 5, 10, 50, 1000)
sets = 1:50
m = 10
K_0 = 1
dim = 1

plot_avg_map_k <- function(dof, ns, m, K_0, dim, sets) {
  pmf = matrix(NA, nrow = m, ncol = length(sets))
  avg_map_k = rep(NA, length(ns))
  sd_map_k = rep(NA, length(ns))
  
  for (i_n in seq_along(ns)) {
    n = ns[i_n]
    
    for (i_set in seq_along(sets)) {
      set = sets[i_set]
      filename = glue("./comp_outputs/student_t/{dim}d/k_posterior-single_t_{dim}d-dof={dof}-n={n}-set-{set}.jld")
      k_posterior = h5read(filename, "k_posterior")
      pmf[, i_set] = k_posterior[1:m]
    }
    
    map_k = apply(pmf, 2, which.max)
    avg_map_k[i_n] = mean(map_k)
    sd_map_k[i_n] = sd(map_k)
  }
  return(list(avg_map_k = avg_map_k, sd_map_k = sd_map_k))
}

mean_df = as.data.frame(ns)
for (dof in dofs) {
  mean_df = cbind(mean_df, plot_avg_map_k(dof, ns, m, K_0, dim, sets)$avg_map_k)
}
sd_df = as.data.frame(ns)
for (dof in dofs) {
  sd_df = cbind(sd_df, plot_avg_map_k(dof, ns, m, K_0, dim, sets)$sd_map_k)
}
colnames(mean_df) <- c("n", dofs)
colnames(sd_df) <- c("n", dofs)

mean_df_long = melt(mean_df,  id.vars = "n", variable.name = "dof")
colnames(mean_df_long) = c("n", "dof", "avg_map_k")

sd_df_long = melt(sd_df,  id.vars = "n", variable.name = "dof")
colnames(sd_df_long) = c("n", "dof", "sd_map_k")

t_1d_long = merge(x = mean_df_long, y = sd_df_long, by = c("n", "dof"))
t_1d_long$upper = t_1d_long$avg_map_k + 2 * t_1d_long$sd_map_k
t_1d_long$lower = t_1d_long$avg_map_k - 2 * t_1d_long$sd_map_k

p = t_1d_long %>%
  ggplot(aes(x = log(n), y = avg_map_k)) +
  geom_line(aes(colour = dof), linewidth = 1) +
  geom_point(aes(color = dof)) +
  scale_x_continuous(name = "log(n)") +
  scale_y_continuous("Avg. MAP number of components", 0:7, limits = c(0, 7)) +
  ggtitle("Single 1D t Component") +
  geom_hline(yintercept = K_0, linetype = 'dotted', col = 'blue') +
  theme(text = element_text(size = 15))
print(p)
ggsave(
  glue("./plots/single_t_1d_results.pdf"),
  p,
  width = 10,
  height = 5,
  dpi = 600,
  units = "in",
  device = "pdf"
)
```

```{r}
for (d in dofs) {
  df = t_1d_long %>%
      filter(dof == d)
  p = df %>% ggplot(aes(x = log(n))) +
    geom_line(aes(colour = dof, y = avg_map_k), linewidth = 1, show.legend = FALSE) +
    geom_line(aes(colour = dof, y = upper), linewidth = 1, show.legend = FALSE) +
    geom_line(aes(colour = dof, y = lower), linewidth = 1, show.legend = FALSE) +
    geom_point(aes(color = dof, y = avg_map_k), show.legend = FALSE) +
    scale_x_continuous(name = "log(n)") +
    scale_y_continuous("Avg. MAP number of components", 1:7, limits = c(1, 7)) +
    ggtitle(glue("Single 1D t Component - dof={d}")) +
    geom_hline(yintercept = K_0, linetype = 'dotted', col = 'blue') +
    theme(text = element_text(size = 18))
    print(p)
  ggsave(
    glue("./plots/single_t_1d_results-dof={d}.pdf"),
    p,
    width = 8,
    height = 5,
    dpi = 600,
    units = "in",
    device = "pdf"
  )
}
```


```{r}
dim = 2
ns = c(100, 250, 500, 750, 1000, 1500, 2500, 5000, 7500, 10000)

plot_avg_map_k <- function(dof, ns, m, K_0, dim, sets) {
  pmf = matrix(NA, nrow = m, ncol = length(sets))
  avg_map_k = rep(NA, length(ns))
  sd_map_k = rep(NA, length(ns))
  
  for (i_n in seq_along(ns)) {
    n = ns[i_n]
    
    for (i_set in seq_along(sets)) {
      set = sets[i_set]
      filename = glue("./comp_outputs/student_t/{dim}d/k_posterior-single_t_{dim}d-dof={dof}-n={n}-set-{set}.jld")
      k_posterior = h5read(filename, "k_posterior")
      pmf[, i_set] = k_posterior[1:m]
    }
    
    map_k = apply(pmf, 2, which.max)
    avg_map_k[i_n] = mean(map_k)
    sd_map_k[i_n] = sd(map_k)
  }
  return(list(avg_map_k = avg_map_k, sd_map_k = sd_map_k))
}

mean_df = as.data.frame(ns)
for (dof in dofs) {
  mean_df = cbind(mean_df, plot_avg_map_k(dof, ns, m, K_0, dim, sets)$avg_map_k)
}
sd_df = as.data.frame(ns)
for (dof in dofs) {
  sd_df = cbind(sd_df, plot_avg_map_k(dof, ns, m, K_0, dim, sets)$sd_map_k)
}
colnames(mean_df) <- c("n", dofs)
colnames(sd_df) <- c("n", dofs)

mean_df_long = melt(mean_df,  id.vars = "n", variable.name = "dof")
colnames(mean_df_long) = c("n", "dof", "avg_map_k")

sd_df_long = melt(sd_df,  id.vars = "n", variable.name = "dof")
colnames(sd_df_long) = c("n", "dof", "sd_map_k")

t_2d_long = merge(x = mean_df_long, y = sd_df_long, by = c("n", "dof"))
t_2d_long$upper = t_2d_long$avg_map_k + 2 * t_2d_long$sd_map_k
t_2d_long$lower = t_2d_long$avg_map_k - 2 * t_2d_long$sd_map_k

p = t_2d_long %>%
  ggplot(aes(x = log(n), y = avg_map_k)) +
  geom_line(aes(colour = dof), linewidth = 1) +
  geom_point(aes(color = dof)) +
  scale_x_continuous(name = "log(n)") +
  scale_y_continuous("Avg. MAP number of components", 0:7, limits = c(0, 7)) +
  ggtitle("Single 2D t Component") +
  geom_hline(yintercept = K_0, linetype = 'dotted', col = 'blue') +
  theme(text = element_text(size = 15))
print(p)
ggsave(
  glue("./plots/single_t_2d_results.pdf"),
  p,
  width = 10,
  height = 5,
  dpi = 600,
  units = "in",
  device = "pdf"
)
```

```{r}
for (d in dofs) {
  df = t_2d_long %>%
      filter(dof == d)
  p = df %>% ggplot(aes(x = log(n))) +
    geom_line(aes(colour = dof, y = avg_map_k), linewidth = 1, show.legend = FALSE) +
    geom_line(aes(colour = dof, y = upper), linewidth = 1, show.legend = FALSE) +
    geom_line(aes(colour = dof, y = lower), linewidth = 1, show.legend = FALSE) +
    geom_point(aes(color = dof, y = avg_map_k), show.legend = FALSE) +
    scale_x_continuous(name = "log(n)") +
    scale_y_continuous("Avg. MAP number of components", 1:10, limits = c(1, 10)) +
    ggtitle(glue("Single 2D t Component - dof={d}")) +
    geom_hline(yintercept = K_0, linetype = 'dotted', col = 'blue') +
    theme(text = element_text(size = 18))
  print(p)
  ggsave(
    glue("./plots/single_t_2d_results-dof={d}.pdf"),
    p,
    width = 8,
    height = 5,
    dpi = 600,
    units = "in",
    device = "pdf"
  )
}
```
```{r}
t_both_df = merge(t_2d_long, t_1d_long, by = c("n", "dof"))
t_both_df$diff = t_both_df$avg_map_k.x - t_both_df$avg_map_k.y
p = t_both_df %>%
  ggplot(aes(x = log(n), y = diff)) +
  geom_line(aes(colour = dof), linewidth = 1) +
  geom_point(aes(color = dof)) +
  scale_x_continuous(name = "log(n)") +
  scale_y_continuous("Difference in avg. MAP number of components") +
  ggtitle("Difference in average MAP number of components (2D minus 1D)") +
  theme(text = element_text(size = 15))

print(p)
ggsave(
  glue("./plots/single_t_2d_1d_diff.pdf"),
  p,
  width = 10,
  height = 5,
  dpi = 600,
  units = "in",
  device = "pdf"
)
```

# Checking convergence
```{r}
alpha = 7
ns = c(5000)

mcmc_its = 10^5
mcmc_burn = 5 * 10^4
mcmc_keep = mcmc_its - mcmc_burn

for (n in ns) {
  filename = glue("./convergence_checks/t_draws-single_skew_normal_1d-alpha={alpha}-n={n}.jld")
  t_draws = h5read(filename, "t_draws")
  df = as.data.frame(cbind(1:100000, t_draws))
  df$class = as.factor(c(rep("burn", mcmc_burn), rep("keep", mcmc_keep)))
  colnames(df) = c("iter", "t", "class")
  p = df %>% 
    mutate(rec = 1) %>% 
    mutate(rollavg = cumsum(t)/cumsum(rec)) %>% 
    select(-rec) %>%
    ggplot() + 
    geom_point(aes(x = iter, y = rollavg, color=class), size = 0.5) +
    scale_y_continuous("Avg. posterior number of clusters") +
    scale_x_continuous("Iteration") +
    ggtitle("Running posterior average number of clusters") +
    theme(text = element_text(size = 16))
  print(p)
  ggsave(
    glue("./plots/post_trace-skew_norm_1d-alpha={alpha}-n={n}-set-{set}.pdf"), 
    p, 
    width = 10, 
    height = 5, 
    units = "in", 
    dpi = 600, 
    device = "pdf"
  )
}

```

```{r}
alpha = 7
ns = c(5000)

mcmc_its = 1 * 10^5
mcmc_burn = 5 * 10^4
mcmc_keep = mcmc_its - mcmc_burn

for (n in ns) {
  filename = glue("./convergence_checks/t_draws-single_skew_normal_2d-alpha={alpha}-n={n}.jld")
  t_draws = h5read(filename, "t_draws")
  df = as.data.frame(cbind(1:mcmc_its, t_draws))
  df$class = as.factor(c(rep("burn", mcmc_burn), rep("keep", mcmc_keep)))
  colnames(df) = c("iter", "t", "class")
  p = df %>% 
    mutate(rec = 1) %>% 
    mutate(rollavg = cumsum(t)/cumsum(rec)) %>% 
    select(-rec) %>%
    ggplot() + 
    geom_point(aes(x = iter, y = rollavg, color=class), size = 0.5) +
    scale_y_continuous("Avg. posterior number of clusters") +
    scale_x_continuous("Iteration") +
    ggtitle("Running posterior average number of clusters") +
    theme(text = element_text(size = 16))
  print(p)
  ggsave(
    glue("./plots/post_trace-skew_norm_2d-alpha={alpha}-n={n}-set-{set}.pdf"), 
    p, 
    width = 10, 
    height = 5, 
    units = "in", 
    dpi = 600, 
    device = "pdf"
  )
}
```

```{r}
dof = 2
ns = c(5000)

mcmc_its = 1 * 10^5
mcmc_burn = 5 * 10^4
mcmc_keep = mcmc_its - mcmc_burn

for (n in ns) {
  filename = glue("./convergence_checks/t_draws-single_t_1d-dof={dof}-n={n}.jld")
  t_draws = h5read(filename, "t_draws")
  df = as.data.frame(cbind(1:mcmc_its, t_draws))
  df$class = as.factor(c(rep("burn", mcmc_burn), rep("keep", mcmc_keep)))
  colnames(df) = c("iter", "t", "class")
  p = df %>% 
    mutate(rec = 1) %>% 
    mutate(rollavg = cumsum(t)/cumsum(rec)) %>% 
    select(-rec) %>%
    ggplot() + 
    geom_point(aes(x = iter, y = rollavg, color=class), size = 0.5) +
    scale_y_continuous("Avg. posterior number of clusters") +
    scale_x_continuous("Iteration") +
    ggtitle("Running posterior average number of clusters") +
    theme(text = element_text(size = 16))
  print(p)
  ggsave(
    glue("./plots/post_trace-t_1d-dof={dof}-n={n}-set-{set}.pdf"), 
    p, 
    width = 10, 
    height = 5, 
    units = "in", 
    dpi = 600, 
    device = "pdf"
  )
}
```


```{r}
dof = 2
ns = c(5000)

mcmc_its = 1 * 10^5
mcmc_burn = 5 * 10^4
mcmc_keep = mcmc_its - mcmc_burn

for (n in ns) {
  filename = glue("./convergence_checks/t_draws-single_t_2d-dof={dof}-n={n}.jld")
  t_draws = h5read(filename, "t_draws")
  df = as.data.frame(cbind(1:mcmc_its, t_draws))
  df$class = as.factor(c(rep("burn", mcmc_burn), rep("keep", mcmc_keep)))
  colnames(df) = c("iter", "t", "class")
  p = df %>% 
    mutate(rec = 1) %>% 
    mutate(rollavg = cumsum(t)/cumsum(rec)) %>% 
    select(-rec) %>%
    ggplot() + 
    geom_point(aes(x = iter, y = rollavg, color=class), size = 0.5) +
    scale_y_continuous("Avg. posterior number of clusters") +
    scale_x_continuous("Iteration") +
    ggtitle("Running posterior average number of clusters") +
    theme(text = element_text(size = 16))
  print(p)
  ggsave(
    glue("./plots/post_trace-t_2d-dof={dof}-n={n}-set-{set}.pdf"), 
    p, 
    width = 10, 
    height = 5, 
    units = "in", 
    dpi = 600, 
    device = "pdf"
  )
}
```

# Visualise some posterior clusterings

```{r}
mcmc_its = 100000
mcmc_burn = 50000
set = 8
alpha = 7
ns = c(100, 500, 1000)

read_name = glue("./data_inputs/skew_norm/2d/single_skew_normal_2d-alpha={alpha}-set-{set}.jld")
all_data = h5read(
  read_name,
  "data"
)
 
# for (n in ns) {
#   data = all_data[1:n, ]
#   post_z_samples = h5read(
#     glue("./comp_outputs/skew_norm/2d/z_draws-single_skew_normal_2d-alpha={alpha}-n={n}-set-{set}.jld"),
#     "z"
#   )
#   post_z_samples = t(post_z_samples[, (mcmc_burn + 1):mcmc_its])
#   psm = comp.psm(post_z_samples)
#   min_vi = minVI(
#     psm,
#     post_z_samples,
#     method = "draws",
#     include.greedy = FALSE
#   )
#   best_vi = min_vi$cl
# 
#   # Create 
#   df = as.data.frame(cbind(data, best_vi))
#   colnames(df) = c("x", "y", "z")
#   save_file = glue("./comp_outputs/skew_norm/2d/summary-single_skew_normal_2d-alpha={alpha}-n={n}-set-{set}.csv")
#   write.csv(df, file = save_file)
# }

for (n in ns) {
  filename = glue("./comp_outputs/skew_norm/2d/summary-single_skew_normal_2d-alpha={alpha}-n={n}-set-{set}.csv")
  df = read.csv(filename)
  df$z = as.factor(as.numeric(as.factor(df$z)))
  summary_clustering_plot = df %>% ggplot(aes(x = x, y = y)) +
    geom_point(aes(color = z), size = 2) +
    scale_color_discrete() +
    ggtitle(glue("Summary Clustering (Best VILB posterior sample) - n={n}")) +
    theme(text = element_text(size = 18))
  print(summary_clustering_plot)
  ggsave(
    glue("./plots/single_skew_norm_summary_clustering-alpha={alpha}-n={n}.pdf"),
    summary_clustering_plot,
    width = 10,
    height = 10,
    units = "in", 
    dpi = 600, 
    device = "pdf"
  )
}
```

Student's t summary clustering
```{r}
mcmc_its = 100000
mcmc_burn = 50000
set = 8
dof = 2
ns = c(100, 500, 1000)

read_name = glue("./data_inputs/student_t/2d/single_t_2d-dof={dof}-set-{set}.jld")
all_data = h5read(
  read_name,
  "data"
)


# for (n in ns) {
#   data = all_data[1:n, ]
#   post_z_samples = h5read(
#     glue("./comp_outputs/student_t/2d/z_draws-single_t_2d-dof={dof}-n={n}-set-{set}.jld"),
#     "z"
#   )
#   post_z_samples = t(post_z_samples[, (mcmc_burn + 1):mcmc_its])
#   
#   psm = comp.psm(post_z_samples)
#   min_vi = minVI(
#     psm,
#     post_z_samples,
#     method = "draws",
#     include.greedy = FALSE
#   )
#   best_vi = min_vi$cl
# 
#   # Create 
#   df = as.data.frame(cbind(data, best_vi))
#   colnames(df) = c("x", "y", "z")
#   save_file = glue("./comp_outputs/student_t/2d/summary-single_t_2d-dof={dof}-n={n}-set-{set}.csv")
#   write.csv(df, file = save_file)
# }


for (n in ns) {
  filename = glue("./comp_outputs/student_t/2d/summary-single_t_2d-dof={dof}-n={n}-set-{set}.csv")
  df = read.csv(filename)
  df$z = as.factor(as.numeric(as.factor(df$z)))
  summary_clustering_plot = df %>% ggplot(aes(x = x, y = y)) +
    geom_point(aes(color = z), size = 2) +
    scale_color_discrete() +
    ggtitle(glue("Summary Clustering (Best VILB posterior sample) - n={n}")) +
    theme(text = element_text(size = 18))
  print(summary_clustering_plot)
  ggsave(
    glue("./plots/single_t_summary_clustering-dof={dof}-n={n}.pdf"),
    summary_clustering_plot,
    width=10, 
    height=10, 
    units="in", 
    dpi=600, 
    device="pdf"
  )
}

```

